name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]
    paths:
      - "functions/**"
      - "firebase.json"
      - "firestore.rules"
      - "firestore.indexes.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORGANIZACIONCENTRO_D3CD7 }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions dependencies
        working-directory: functions
        run: npm ci

      - name: Lint Functions
        working-directory: functions
        run: npm run -s lint

      - name: Deploy Functions and Firestore Rules
        run: firebase deploy --only functions,firestore:rules --project organizacioncentro-d3cd7 --non-interactive
